### ISSUE TITLE
finalize data.main_polymake_session atexit

### ISSUE THREAD

**Issue by kalmarek** [oscar-system/Polymake.jl#340]
as pointed by Eugen on riot

**Comment by benlorenz** [comment]
This should not be necessary as it is done automatically by the global destructor (via `__attribute__((destructor))`). Also julia runs all `atexit` code and finalizers explicitly before exit so the order is also correct.

_Full details:_
julia calls all cleanup functions explicitly before exit from main:
```
#0  jl_gc_run_all_finalizers (ptls=0x7f30c6eb8740) at /software/julia/julia-git/src/gc.c:447
#1  0x00007f30c696f3db in jl_atexit_hook (exitcode=<optimized out>) at /software/julia/julia-git/src/init.c:240
#2  0x00007f30c69ad8da in repl_entrypoint (argc=<optimized out>, argv=<optimized out>) at /software/julia/julia-git/src/jlapi.c:700
#3  0x000055f77d89c069 in main (argc=<optimized out>, argv=<optimized out>) at /software/julia/julia-git/cli/loader_exe.c:51
```

polymake and perl cleanup is triggered with `exit`:
```
#0  0x00007f308a32bb90 in perl_destruct () from /software/julia/depots/julia-git/artifacts/06ceadfe6189348f596024106c6a86d1d0ae2273/lib/libperl.so
#1  0x00007f3082244a13 in pm::perl::(anonymous namespace)::destroy_perl(interpreter*) ()
   from /software/julia/depots/julia-git/artifacts/c2e908f420af909af6125716f044b1f7635ee267/lib/libpolymake.so
#2  0x00007f30821c5b78 in pm::perl::(anonymous namespace)::emergency_cleanup() ()
   from /software/julia/depots/julia-git/artifacts/c2e908f420af909af6125716f044b1f7635ee267/lib/libpolymake.so
#3  0x00007f30c70f7a04 in _dl_fini () at dl-fini.c:139
#4  0x00007f30c6f289c3 in __run_exit_handlers (status=0, listp=0x7f30c70a9598 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true)
    at exit.c:108
#5  0x00007f30c6f28b7c in __GI_exit (status=<optimized out>) at exit.c:139
#6  0x000055f77d89c070 in main (argc=<optimized out>, argv=<optimized out>) at /software/julia/julia-git/cli/loader_exe.c:54
```

In the backtraces the finalizers are triggered via line 51 in `loader_exe.c` whereas the `_dl_fini` (for the global destructor) comes from line 54 where `exit` called.
```
51:    int ret = jl_load_repl(argc, argv);                                                                                                                              
52:                                                                                                                                                                     
53:    // On Windows we're running without the CRT that would do this for us
54:    exit(ret);
55:    return ret;
56: }
```

So: `main` calls `jl_load_repl` which will run the repl with `repl_entrypoint`; just before returning `repl_entrypoint` will call `jl_atexit_hook` (which also runs the finalizers).
When `repl_entrypoint` is done `main` will call `exit` which then triggers the global destructor for `perl_destruct`.

I.e. all polymake objects julia knows about will be properly garbage collected and cleaned up (via cxxwrap calling the destructors) before the final polymake+perl cleanup is called.
